#!/usr/bin/env bash
#
# run.sh — one-shot launcher for the full VGuardrail stack.
#
# Builds and runs the backend (Rust/Axum) + dashboard (Next.js) containers
# against the provisioned AWS dev data-plane, publishes their ports to the
# host, and health-checks. Idempotent — safe to re-run.
#
#   ./run.sh            build + up + health-check (default)
#   ./run.sh down       stop and remove the stack
#   ./run.sh logs       follow logs
#
set -euo pipefail
cd "$(dirname "$0")"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
ok()  { printf '\033[1;32m    %s\033[0m\n' "$*"; }
warn(){ printf '\033[1;33m    %s\033[0m\n' "$*"; }
die() { printf '\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# Base prod compose + a generated override that publishes ports and forwards
# AWS creds into the backend container (prod compose keeps ports internal).
OVERRIDE=.compose.run.yml
COMPOSE=(docker compose -f docker-compose.yml -f "$OVERRIDE")

write_override() {
  cat > "$OVERRIDE" <<'YAML'
# Generated by run.sh — publishes ports + forwards host AWS creds for local runs.
services:
  backend:
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-}"
      AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN:-}"
  dashboard:
    ports:
      - "3000:3000"
YAML
}

# Sub-commands ---------------------------------------------------------------
case "${1:-up}" in
  down) write_override; exec "${COMPOSE[@]}" down ;;
  logs) write_override; exec "${COMPOSE[@]}" logs -f ;;
  up|"") ;;
  *) die "unknown command '$1' (use: up | down | logs)" ;;
esac

# 1. Prerequisites -----------------------------------------------------------
[ -f .env ] || die ".env not found — copy .env.example and fill it, or run terraform (backend/terraform/stacks/dev)"

log "Checking Docker daemon"
if ! docker info >/dev/null 2>&1; then
  warn "daemon down — launching Docker Desktop"
  open -a Docker 2>/dev/null || die "could not launch Docker Desktop"
  for _ in $(seq 1 60); do docker info >/dev/null 2>&1 && break; sleep 2; done
  docker info >/dev/null 2>&1 || die "Docker daemon did not come up"
fi
ok "Docker $(docker version --format '{{.Server.Version}}' 2>/dev/null)"

# 2. AWS credentials (for in-container Dynamo/S3/Cognito ops) -----------------
log "Loading AWS credentials"
if command -v aws >/dev/null 2>&1 && eval "$(aws configure export-credentials --format env 2>/dev/null)"; then
  export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN 2>/dev/null || true
  ok "credentials loaded (account $(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo '?'))"
else
  warn "no AWS credentials — backend will still boot (JWKS is public) but data ops will fail"
fi

# 3. Infra sanity: is the Cognito JWKS endpoint live? ------------------------
ISS=$(grep -E '^VG_COGNITO_ISSUER=' .env | cut -d= -f2- || true)
if [ -n "${ISS:-}" ]; then
  log "Checking provisioned Cognito pool"
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 8 "$ISS/.well-known/jwks.json" 2>/dev/null || echo 000)
  [ "$code" = "200" ] && ok "JWKS reachable ($ISS)" \
    || warn "JWKS NOT reachable (HTTP $code) — provision infra: (cd backend/terraform/stacks/dev && terraform apply)"
fi

# 4. Build -------------------------------------------------------------------
write_override
log "Building images (first run compiles the Rust release — a few minutes; cached after)"
"${COMPOSE[@]}" build

# 5. Up ----------------------------------------------------------------------
log "Starting stack"
"${COMPOSE[@]}" up -d

# 6. Health check ------------------------------------------------------------
log "Waiting for backend /health"
healthy=
for _ in $(seq 1 30); do
  code=$(curl -s -o /tmp/vg_health.json -w '%{http_code}' http://localhost:8080/health 2>/dev/null || echo 000)
  if [ "$code" = "200" ]; then healthy=1; break; fi
  sleep 2
done
[ -n "$healthy" ] || { "${COMPOSE[@]}" logs backend | tail -25; die "backend /health did not return 200"; }
ok "backend /health -> 200 $(cat /tmp/vg_health.json)"

dash=$(curl -s -o /dev/null -w '%{http_code}' --max-time 12 http://localhost:3000/ 2>/dev/null || echo 000)
ok "dashboard /     -> $dash (200/3xx = loads)"

# 7. Done --------------------------------------------------------------------
log "Stack is up"
cat <<EOF
    Backend:   http://localhost:8080/health
    Dashboard: http://localhost:3000
    Logs:      ./run.sh logs
    Stop:      ./run.sh down
EOF
