#!/usr/bin/env bash
#
# VGuardrail CLI wrapper installer
#
# Builds the CLI connector framework and all adapters, then installs
# vg-claude / vg-gemini / vg-codex / vg-aider / vg-ollama / vg-llama /
# vg-mlx / vg-sgpt / vg-gh-copilot launcher scripts.
#
# Usage:
#   ./install-wrappers.sh                 # build + install launchers
#   ./install-wrappers.sh --shadow        # also offer shell aliases (claude -> vg-claude, ...)
#   ./install-wrappers.sh --uninstall     # remove launchers + alias block
#   ./install-wrappers.sh --skip-build    # install launchers without rebuilding
#   PREFIX=/opt/vguardrail ./install-wrappers.sh   # install into $PREFIX/bin
#
# Safety guarantees:
#   - NEVER renames, moves, or modifies the original tool binaries.
#   - Shadowing is done via shell aliases only, and only with explicit
#     confirmation before ~/.zshrc is touched.
#   - Idempotent: safe to re-run; launchers and the alias block are
#     replaced in place.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

PREFIX="${PREFIX:-/usr/local}"
BIN_DIR="${PREFIX}/bin"
ZSHRC="${HOME}/.zshrc"

LAUNCHER_MARKER="# VGuardrail launcher (generated by install-wrappers.sh)"
ALIAS_BEGIN="# >>> vguardrail cli wrappers >>>"
ALIAS_END="# <<< vguardrail cli wrappers <<<"

# tool name -> adapter directory (launcher is vg-<tool>)
TOOLS=(claude gemini codex aider ollama llama mlx sgpt gh-copilot)

# Packages in dependency order: framework first, then adapters.
PACKAGES=(
  "framework"
  "adapters/claude"
  "adapters/gemini"
  "adapters/codex"
  "adapters/aider"
  "adapters/ollama"
  "adapters/llama"
  "adapters/mlx"
  "adapters/sgpt"
  "adapters/gh-copilot"
)

# Real command(s) a wrapper shadows, when they differ from the tool name.
# vg-gh-copilot wraps the `gh` binary; llama.cpp's CLI has been renamed
# across versions (llama-cli, formerly main); vg-mlx wraps mlx_lm.generate.
alias_commands_for() {
  case "$1" in
    gh-copilot) echo "gh" ;;
    llama)      echo "llama-cli llama" ;;
    mlx)        echo "mlx_lm.generate" ;;
    *)          echo "$1" ;;
  esac
}

DO_SHADOW=0
DO_UNINSTALL=0
DO_BUILD=1

log()  { printf '[vguardrail] %s\n' "$*"; }
warn() { printf '[vguardrail] WARNING: %s\n' "$*" >&2; }
die()  { printf '[vguardrail] ERROR: %s\n' "$*" >&2; exit 1; }

usage() {
  sed -n '2,22p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

# ── argument parsing ──────────────────────────────────────────────────────────

for arg in "$@"; do
  case "${arg}" in
    --shadow)     DO_SHADOW=1 ;;
    --uninstall)  DO_UNINSTALL=1 ;;
    --skip-build) DO_BUILD=0 ;;
    -h|--help)    usage; exit 0 ;;
    *)            die "Unknown option: ${arg} (see --help)" ;;
  esac
done

# ── helpers ───────────────────────────────────────────────────────────────────

# Run a command, falling back to sudo with a clear message when the
# target location is not writable.
run_privileged() {
  if "$@" 2>/dev/null; then
    return 0
  fi
  if command -v sudo >/dev/null 2>&1; then
    warn "${BIN_DIR} is not writable by $(id -un); retrying with sudo."
    warn "To avoid sudo, re-run with PREFIX set to a writable location, e.g.:"
    warn "  PREFIX=\$HOME/.local $0"
    sudo "$@"
  else
    die "Cannot write to ${BIN_DIR} and sudo is unavailable. Re-run with PREFIX=\$HOME/.local"
  fi
}

# Remove the alias block from ~/.zshrc (idempotent, no-op when absent).
remove_alias_block() {
  [ -f "${ZSHRC}" ] || return 0
  if grep -qF "${ALIAS_BEGIN}" "${ZSHRC}"; then
    local tmp
    tmp="$(mktemp)"
    awk -v begin="${ALIAS_BEGIN}" -v end="${ALIAS_END}" '
      $0 == begin { skipping = 1; next }
      $0 == end   { skipping = 0; next }
      !skipping   { print }
    ' "${ZSHRC}" > "${tmp}"
    mv "${tmp}" "${ZSHRC}"
    log "Removed alias block from ${ZSHRC}"
  fi
}

# ── uninstall ─────────────────────────────────────────────────────────────────

uninstall() {
  log "Uninstalling VGuardrail CLI launchers from ${BIN_DIR}"
  for tool in "${TOOLS[@]}" "claude-hook"; do
    local launcher="${BIN_DIR}/vg-${tool}"
    if [ -f "${launcher}" ]; then
      if grep -qF "${LAUNCHER_MARKER}" "${launcher}" 2>/dev/null; then
        run_privileged rm -f "${launcher}"
        log "Removed ${launcher}"
      else
        warn "Skipping ${launcher}: not a generated VGuardrail launcher."
      fi
    fi
  done
  remove_alias_block
  log "Uninstall complete. Original tool binaries were never touched."
  log "Note: run ./scripts/install-claude-hook.sh --uninstall to remove the Claude Code hook entries from ~/.claude/settings.json."
}

# ── build ─────────────────────────────────────────────────────────────────────

build_all() {
  command -v npm >/dev/null 2>&1 || die "npm is required to build the connectors."
  log "Building framework and adapters (npm install + build, dependency order)"
  for pkg in "${PACKAGES[@]}"; do
    local dir="${ROOT_DIR}/${pkg}"
    [ -d "${dir}" ] || die "Missing package directory: ${dir}"
    log "  -> ${pkg}: npm install"
    (cd "${dir}" && npm install --no-audit --no-fund --loglevel=error)
    log "  -> ${pkg}: npm run build"
    (cd "${dir}" && npm run build --silent)
  done
}

# ── launcher install ──────────────────────────────────────────────────────────

install_launchers() {
  local node_bin
  node_bin="$(command -v node)" || die "node is required to run the wrappers."

  if [ ! -d "${BIN_DIR}" ]; then
    run_privileged mkdir -p "${BIN_DIR}"
  fi

  for tool in "${TOOLS[@]}"; do
    local adapter_entry="${ROOT_DIR}/adapters/${tool}/bin/vg-${tool}.js"
    local launcher="${BIN_DIR}/vg-${tool}"

    [ -f "${adapter_entry}" ] || die "Adapter entry not found: ${adapter_entry} (build failed?)"
    if [ ! -f "${ROOT_DIR}/adapters/${tool}/dist/index.js" ]; then
      warn "adapters/${tool}/dist/index.js is missing; vg-${tool} will fail until it is built."
    fi

    local tmp
    tmp="$(mktemp)"
    cat > "${tmp}" <<EOF
#!/bin/sh
${LAUNCHER_MARKER}
# Wraps the '${tool}' CLI with VGuardrail policy enforcement.
# Local dev: when vguardiand runs as a per-user LaunchAgent (not the system
# LaunchDaemon), the XPC lookup must target the user domain.
if [ -f "\$HOME/Library/LaunchAgents/com.vguardrail.agent.local.plist" ]; then
  VG_XPC_USER_AGENT=1
  export VG_XPC_USER_AGENT
fi
exec "${node_bin}" "${adapter_entry}" "\$@"
EOF
    chmod 0755 "${tmp}"
    run_privileged cp "${tmp}" "${launcher}"
    rm -f "${tmp}"
    log "Installed ${launcher}"
  done

  # vg-claude-hook: the Claude Code hook binary (separate bin in the claude
  # adapter). It is invoked by Claude Code with a JSON event on stdin; the
  # launcher mirrors the wrappers' user-domain XPC handling.
  local hook_entry="${ROOT_DIR}/adapters/claude/bin/vg-claude-hook.js"
  if [ -f "${hook_entry}" ]; then
    local hook_launcher="${BIN_DIR}/vg-claude-hook"
    local tmp
    tmp="$(mktemp)"
    cat > "${tmp}" <<EOF
#!/bin/sh
${LAUNCHER_MARKER}
# VGuardrail hook for Claude Code (UserPromptSubmit / PreToolUse).
if [ -f "\$HOME/Library/LaunchAgents/com.vguardrail.agent.local.plist" ]; then
  VG_XPC_USER_AGENT=1
  export VG_XPC_USER_AGENT
fi
exec "${node_bin}" "${hook_entry}" "\$@"
EOF
    chmod 0755 "${tmp}"
    run_privileged cp "${tmp}" "${hook_launcher}"
    rm -f "${tmp}"
    log "Installed ${hook_launcher}"
  fi
}

# ── shadow mode (aliases only, never touches real binaries) ──────────────────

shadow() {
  log "Shadow mode: recommending shell aliases (original binaries are NEVER renamed or moved)."

  # Entries are "<command>=vg-<tool>" (the shadowed command can differ
  # from the tool name, e.g. gh -> vg-gh-copilot).
  local found_aliases=()
  for tool in "${TOOLS[@]}"; do
    local matched=0
    for cmd in $(alias_commands_for "${tool}"); do
      if command -v "${cmd}" >/dev/null 2>&1; then
        found_aliases+=("${cmd}=vg-${tool}")
        matched=1
      fi
    done
    if [ "${matched}" -eq 0 ]; then
      log "  ${tool}: wrapped command not found on PATH; skipping alias recommendation."
    fi
  done

  if [ "${#found_aliases[@]}" -eq 0 ]; then
    log "No wrapped tools found on PATH; nothing to shadow."
    return 0
  fi

  echo ""
  echo "Recommended aliases:"
  for entry in "${found_aliases[@]}"; do
    echo "  alias ${entry%%=*}='${entry#*=}'"
  done
  echo ""

  printf 'Append these aliases to %s? [y/N] ' "${ZSHRC}"
  local answer=""
  read -r answer || true
  case "${answer}" in
    y|Y|yes|YES)
      remove_alias_block  # idempotent: replace any previous block
      {
        echo "${ALIAS_BEGIN}"
        for entry in "${found_aliases[@]}"; do
          echo "alias ${entry%%=*}='${entry#*=}'"
        done
        echo "${ALIAS_END}"
      } >> "${ZSHRC}"
      log "Aliases appended to ${ZSHRC}. Run 'source ${ZSHRC}' or open a new shell."
      ;;
    *)
      log "Skipped. You can add the aliases manually at any time."
      ;;
  esac
}

# ── main ──────────────────────────────────────────────────────────────────────

if [ "${DO_UNINSTALL}" -eq 1 ]; then
  uninstall
  exit 0
fi

if [ "${DO_BUILD}" -eq 1 ]; then
  build_all
else
  log "Skipping build (--skip-build)."
fi

install_launchers

if [ "${DO_SHADOW}" -eq 1 ]; then
  shadow
fi

log "Done. Launchers installed in ${BIN_DIR}: $(printf 'vg-%s ' "${TOOLS[@]}")"
log "Emergency bypass: pass --bypass (or set VG_BYPASS=1) to skip scanning; this is loud and audited."
