// Shared pagination contract for the BFF layer.
//
// Wire format (matches the contract the future backend lambdas will use):
//
//   Query string:
//     page=2&per_page=25&search=foo&sort_by=last_seen_ms&sort_dir=desc
//
//   Response envelope:
//     {
//       "items":       [ ... ],
//       "page":        2,
//       "per_page":    25,
//       "total":       137,
//       "next_token":  "3:25"
//     }
//
// The `next_token` field is the only thing the client should use to walk
// the result set. It is opaque (free-form string) and is generated by the
// route handler; the mock layer happens to use a `<page>:<per_page>` scheme
// but the real backend is free to use cursors.

import { NextRequest } from "next/server";
import { badRequestError } from "@/lib/api/errors";
import {
  apiCreated,
  apiError,
  apiNoContent,
  apiSuccess,
  readJson,
} from "@/lib/api/response";
import type { Page, PageQuery } from "@/lib/api/types";

export const DEFAULT_PAGE = 1;
export const DEFAULT_PER_PAGE = 25;
export const MAX_PER_PAGE = 100;

export interface RawPagination {
  readonly page: number;
  readonly perPage: number;
  readonly search?: string;
  readonly sortBy?: string;
  readonly sortDir?: "asc" | "desc";
}

export interface PaginationError {
  readonly status: number;
  readonly message: string;
}

const parseBoundedInt = (
  raw: string | null,
  fallback: number,
  min: number,
  max: number,
  name: string
): number => {
  if (raw === null || raw === "") return fallback;
  if (!/^\d+$/.test(raw)) {
    throw badRequestError(`${name} must be an integer`);
  }
  const parsed = Number.parseInt(raw, 10);
  if (parsed < min || parsed > max) {
    throw badRequestError(`${name} must be between ${min} and ${max}`);
  }
  return parsed;
};

const clampSearch = (raw: string | null): string | undefined => {
  if (raw === null) return undefined;
  const trimmed = raw.trim();
  return trimmed.length > 0 ? trimmed.slice(0, 200) : undefined;
};

const normalizeSort = (
  raw: string | null,
  allowed: ReadonlySet<string>
): string | undefined => {
  if (raw === null || raw === "") return undefined;
  return allowed.has(raw) ? raw : undefined;
};

const normalizeDir = (raw: string | null): "asc" | "desc" | undefined => {
  if (raw === null) return undefined;
  const lower = raw.toLowerCase();
  return lower === "asc" || lower === "desc" ? lower : undefined;
};

/**
 * Parse pagination query parameters from a Next.js request.
 * Returns a typed object suitable for passing to a repository `list()` call.
 */
export function parsePagination(
  req: NextRequest,
  options: {
    readonly allowedSortFields?: readonly string[];
    readonly defaultPerPage?: number;
  } = {}
): RawPagination {
  const params = req.nextUrl.searchParams;
  const allowedSort = new Set(options.allowedSortFields ?? []);
  const perPage = parseBoundedInt(
    params.get("per_page"),
    options.defaultPerPage ?? DEFAULT_PER_PAGE,
    1,
    MAX_PER_PAGE,
    "per_page"
  );
  const page = parseBoundedInt(
    params.get("page"),
    DEFAULT_PAGE,
    1,
    10_000,
    "page"
  );
  return {
    page,
    perPage,
    ...(clampSearch(params.get("search"))
      ? { search: clampSearch(params.get("search"))! }
      : {}),
    ...(normalizeSort(params.get("sort_by"), allowedSort)
      ? { sortBy: normalizeSort(params.get("sort_by"), allowedSort)! }
      : {}),
    ...(normalizeDir(params.get("sort_dir"))
      ? { sortDir: normalizeDir(params.get("sort_dir"))! }
      : {}),
  };
}

/** Convert a Page into the BFF response envelope. */
export function toPageResponse<T>(page: Page<T>): {
  items: readonly T[];
  page: number;
  per_page: number;
  total: number;
  next_token: string | null;
} {
  return {
    items: page.items,
    page: page.page,
    per_page: page.perPage,
    total: page.total,
    next_token: page.nextToken,
  };
}

export function toPageQuery(raw: RawPagination): PageQuery {
  const q: {
    page: number;
    perPage: number;
    search?: string;
    sortBy?: string;
    sortDir?: "asc" | "desc";
  } = { page: raw.page, perPage: raw.perPage };
  if (raw.search) q.search = raw.search;
  if (raw.sortBy) q.sortBy = raw.sortBy;
  if (raw.sortDir) q.sortDir = raw.sortDir;
  return q;
}

export function ok<T>(data: T, init: ResponseInit = {}) {
  return apiSuccess(data, init);
}

export function created<T>(data: T) {
  return apiCreated(data);
}

export function noContent() {
  return apiNoContent();
}

export function badRequest(message: string) {
  return apiError("bad_request", message, 400);
}

export function unauthorized(message = "Authentication required") {
  return apiError("unauthorized", message, 401);
}

export function forbidden(message = "Insufficient role") {
  return apiError("forbidden", message, 403);
}

export function notFound(message = "Not found") {
  return apiError("not_found", message, 404);
}

export function serverError(message = "Internal server error") {
  return apiError("internal_error", message, 500);
}

export { readJson };
